version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.3.1
  - dependency-name: ajax-datatables-rails
    versions:
    - 1.3.0
